paths:
  /serve/kittens:
    basePrice: 10000
    localPath: ~/Documents/Kittens
    priceMode: pricePerFile
  /serve/kittens/kitty.jpg:
    basePrice: 10000
    localPath: ~/Documents/Kittens/red.jpeg
    priceMode: pricePerFile
  /serve/public/ppb:
    basePrice: 0.1  #satoshi per byte
    priceMode: payPerByte_full

