##
# This is the travis yaml file that travis-ci uses to run the tests
# Travis currently cannot run python apps on Max OSX like it can on linux.
# The fix is to use a gneric language and brew install the python version
# being tested and create a virtual env manually. It's a hack but it works
# until the enable native python support for python on OSX.
language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 3.5
          sudo: false
        # Use generic language for osx
        - os: osx
          language: generic
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
# Install prereqs and run mkrelease to create TWO1_VERSION
install:
    - pip install -r requirements.txt
    - python two1/commands/util/mkrelease.py
# run those tests!
script: python -m pytest
