language: python
python: "3.5"
# command to install dependencies
install:
    # need to make the version string off of the git tag
    - pip install -r requirements.txt
    - python two1/commands/util/mkrelease.py
# command to run tests
script: py.test
