"""
Script to dynamically generate the README.

```
python3 generate_readme.py
```
"""
from itertools import groupby
import ast
import glob
import os


def get_docstring(filename):
    module = ast.parse(open(filename).read())
    docstring = ast.get_docstring(module)
    return docstring.split('\n')[0] if docstring else docstring


def get_template():
    """
    Retrieve the template from which contains the README is generated.
    """
    return open('README.md.template').read()


def generate_watermark():
    """
    An HTML comment.
    """
    return (
        '<!--- Do not edit this file directly!\n'
        'This file was dynamically generated from README.md.template.\n'
        'Edit that and then run python3 generate_readme.py -->\n'
    )


def generate_codebase():
    """
    Generate the "The Codebase" main section of the README.
    """
    yield('# The Codebase')
    filenames = filter(
        get_docstring, glob.iglob('two1/**/*py', recursive=True))
    for directory, filenames in groupby(filenames, os.path.dirname):
        yield('## The `%s` directory' % directory)
        for filename in filenames:
            yield(' - [%s](%s): %s' % (
                os.path.basename(filename), filename, get_docstring(filename)))
        yield('')

if __name__ == '__main__':
    template = get_template()
    with open('README.md', 'w') as f:
        f.write(
            # Poor man's templating rendering engine
            template
            .replace('{WATERMARK}', generate_watermark())
            .replace('{CODEBASE}', '\n'.join(generate_codebase()))
        )
