basePath: /
definitions:
  Server:
    properties:
      city: {type: string}
      provider: {type: string}
      public_ip: {type: string}
      state: {type: string}
      zip_code: {type: string}
    type: object
host: ""
info:
  version: 1.0.0
  x-21-implements: ['31c7a5f5cb76ad33771180fbca39dd20376c3439']
  contact: {email: nakamoto@nakamoto.com, name: Satoshi Nakamoto}
  description: Run a ping on demand for bitcoin.
  title: ping21
  x-21-category: utilities
  x-21-github-project-url: https://github.com/21dotco/ping21
  x-21-keywords: [ping, network]
  x-21-quick-buy: "$ 21 buy http://%s:%s/%s/?uri=21.co"
  x-21-total-price: {max: 3000, min: 3000}
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Ping statistics and information on server location.
          schema:
            properties:
              ping:
                items: {type: string}
                type: array
              server: {$ref: '#/definitions/Server'}
            type: object
      summary: Return ping statistics between this device and a given domain
        or IP.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
