sudo: required
language: cpp
os:
  - linux
  - osx
script:
  - ./travis.sh $CONFIG
env:
  - CONFIG=cpp
  - CONFIG=cpp_distcheck
  - CONFIG=csharp
  - CONFIG=java_jdk6
  - CONFIG=java_jdk7
  - CONFIG=java_oracle7
  - CONFIG=javanano_jdk6
  - CONFIG=javanano_jdk7
  - CONFIG=javanano_oracle7
  - CONFIG=python
  - CONFIG=python_cpp
  - CONFIG=ruby19
  - CONFIG=ruby20
  - CONFIG=ruby21
  - CONFIG=ruby22
  - CONFIG=jruby
notifications:
  email: false
