version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  minimal:
    format: "%(name)s : %(message)s\n-------------------------------------"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: minimal
    stream: ext://sys.stdout

  file_handler:

      class: logging.handlers.RotatingFileHandler

      formatter: simple

      filename: ./logs/app.log

      maxBytes: 10485760 # 10MB

      backupCount: 20

      encoding: utf8

root:
  level: DEBUG
  handlers: [console, file_handler]